### PR TITLE
Problem: AddressValidator.isValid() is expected to return boolean, but will throw

### LINKED ISSUE #137: Problem: AddressValidator.isValid() is expected t return boolean, but will throw
`isValid()` is expected to return false on error, but when the bech32 encoding is wrong, it throws Error.

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: (Fix #137) Return false on error

### CODE REVIEW

**Comment by calvinlauco** [comment]
@eddycpc @crypto-matto any chance this will affect existing projects?

Because I think the method signature should clear delivers that it is returning a boolean, but not throwing a boolean. But the previous behaviour is not.

File: lib/src/utils/address.ts [hunk 1]
```diff
@@ -40,6 +40,10 @@ export class AddressValidator {
     }
 
     public isValid(): boolean {
-        return validateAddress(this.params);
+        try {
+            return validateAddress(this.params);
+        } catch {
+            return false;
+        }
     }
```
Comment (eddycpc) [inline lib/src/utils/address.ts:48]: Remember we had a call on this initially, we kept it this way because we needed the library users to get the actual error, the underline error message that could come straight from `bech32` encoding checking.

Here's what I would suggest, we make 2 functions :

- `AddressValidator.validate()`: This one should be let to throw, this should be used when the downstream user wants to know really why a certain validation failed

- `AddressValidator.isValid()`: This should be like what's being done in this PR


This way we get the advantage of both worlds since not throwing is not always the best approach in certain scenarios

**Review by eddycpc — CHANGES_REQUESTED** [review]

File: lib/src/utils/address.ts (hunk 1 above)
Comment (calvinaco) [reply lib/src/utils/address.ts:48]: Thanks @eddycpc for the context. Yes I totally agree. I think the goal is to have the behaviour of the functions align with the naming of it.

I will leave this PR open a while until we got clear feedback from the team members and give them enough time to aware of this changes first.

Comment (calvinaco) [reply lib/src/utils/address.ts:48]: I will add the `validate()` method to it.

File: lib/src/utils/address.ts [hunk 2]
```diff
@@ -39,7 +39,15 @@ export class AddressValidator {
         this.params = params;
     }
 
-    public isValid(): boolean {
+    public validate(): boolean | never {
```
Comment (eddycpc) [inline lib/src/utils/address.ts:42]: We can add a test for this case too, where we expect it to throw.

**Review by eddycpc — APPROVED** [review]

File: lib/src/utils/address.ts (hunk 2 above)
Comment (calvinaco) [reply lib/src/utils/address.ts:42]: Yes, I have added it here
https://github.com/crypto-com/chain-jslib/pull/138/files#diff-148301d26bbb65e5489940924fddf4a58916bacbb157656f7f10e88e0eee8a7bR56-R67
